/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _page1_page()
*  @super _page
*  @constructor
*  @memberOf _page1_page 
*/
function _page1_page() {
}

//inherit _page
_page1_page.prototype = new _page("page1");

// widget assist
_page1_page.prototype.header1 = undefined;
_page1_page.prototype.content1 = undefined;
_page1_page.prototype.htmlblock1 = undefined;
_page1_page.prototype.heading3 = undefined;
_page1_page.prototype.button1 = undefined;
_page1_page.prototype.button2 = undefined;

// default widget event handler
_page1_page.prototype.button1_ontap = function(event) {};
_page1_page.prototype.button2_ontap = function(event) {};

_page1_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.header1 = $("#page1 #header1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.content1 = $("#page1 #content1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.htmlblock1 = $("#page1 #htmlblock1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.heading3 = $("#page1 #heading3");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.button1 = $("#page1 #button1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.button2 = $("#page1 #button2");

		// bind widget event handler
		_page1_page.prototype.button1.bind("tap", function(event) { _page1_page.prototype.button1_ontap(event); });
		_page1_page.prototype.button2.bind("tap", function(event) { _page1_page.prototype.button2_ontap(event); });

	}, isStartPage);

};
